/**
 * KPI Card Definitions
 * Static configuration for all Executive Dashboard KPI cards
 */
import {
  MdAttachMoney,
  MdTrendingUp,
  MdPeople,
  MdBookmarkBorder,
  MdConfirmationNumber,
  MdCardMembership,
  MdAttractions,
  MdLocalParking,
  MdRestaurant,
  MdStorefront,
  MdMoneyOff,
  MdSentimentSatisfied,
  MdAccountBalance,
  MdBuildCircle,
  MdSwapHoriz,
} from 'react-icons/md';
import type { IconType } from 'react-icons';

export interface KpiDefinition {
  key: string;
  label: string;
  icon: IconType;
  color: 'primary' | 'success' | 'warning' | 'error' | 'info';
  format: 'currency' | 'number' | 'percentage';
  description: string;
  gridSize: { xs: number; sm: number; md: number; lg: number };
  allowedRoles?: string[];
}

export const KPI_DEFINITIONS: KpiDefinition[] = [
  {
    key: 'totalRevenue',
    label: 'Tổng doanh thu',
    icon: MdAttachMoney,
    color: 'primary',
    format: 'currency',
    description: 'Tổng doanh thu trên tất cả địa điểm và kênh bán hàng',
    gridSize: { xs: 12, sm: 6, md: 4, lg: 3 },
    allowedRoles: ['SYSTEM_ADMIN', 'PARK_MANAGER', 'SALES_STAFF'],
  },
  {
    key: 'revenueGrowth',
    label: 'Tăng trưởng doanh thu',
    icon: MdTrendingUp,
    color: 'success',
    format: 'percentage',
    description: 'Tỷ lệ tăng trưởng doanh thu so với kỳ trước',
    gridSize: { xs: 12, sm: 6, md: 4, lg: 3 },
    allowedRoles: ['SYSTEM_ADMIN'],
  },
  {
    key: 'visitorsToday',
    label: 'Lượt khách hôm nay',
    icon: MdPeople,
    color: 'info',
    format: 'number',
    description: 'Tổng số khách vào cổng hôm nay',
    gridSize: { xs: 12, sm: 6, md: 4, lg: 3 },
    allowedRoles: ['SYSTEM_ADMIN', 'PARK_MANAGER', 'SALES_STAFF', 'OPERATIONS_STAFF'],
  },
  {
    key: 'bookingsToday',
    label: 'Đặt vé hôm nay',
    icon: MdBookmarkBorder,
    color: 'primary',
    format: 'number',
    description: 'Số lượt đặt vé mới trong ngày hôm nay',
    gridSize: { xs: 12, sm: 6, md: 4, lg: 3 },
    allowedRoles: ['SYSTEM_ADMIN', 'PARK_MANAGER', 'SALES_STAFF'],
  },
  {
    key: 'ticketsSold',
    label: 'Số vé đã bán',
    icon: MdConfirmationNumber,
    color: 'success',
    format: 'number',
    description: 'Tổng số vé bán ra trong kỳ được chọn',
    gridSize: { xs: 12, sm: 6, md: 4, lg: 3 },
    allowedRoles: ['SYSTEM_ADMIN', 'PARK_MANAGER', 'SALES_STAFF'],
  },
  {
    key: 'activeMemberships',
    label: 'Thành viên hoạt động',
    icon: MdCardMembership,
    color: 'primary',
    format: 'number',
    description: 'Số tài khoản thành viên đang hoạt động',
    gridSize: { xs: 12, sm: 6, md: 4, lg: 3 },
    allowedRoles: ['SYSTEM_ADMIN'],
  },
  {
    key: 'rideUtilization',
    label: 'Hiệu suất trò chơi',
    icon: MdAttractions,
    color: 'info',
    format: 'percentage',
    description: 'Hiệu suất khai thác sức chứa trung bình của trò chơi',
    gridSize: { xs: 12, sm: 6, md: 4, lg: 3 },
    allowedRoles: ['SYSTEM_ADMIN', 'PARK_MANAGER', 'OPERATIONS_STAFF'],
  },
  {
    key: 'parkingUsage',
    label: 'Hiệu suất đỗ xe',
    icon: MdLocalParking,
    color: 'warning',
    format: 'percentage',
    description: 'Tỷ lệ lấp đầy hiện tại của bãi đỗ xe',
    gridSize: { xs: 12, sm: 6, md: 4, lg: 3 },
    allowedRoles: ['SYSTEM_ADMIN', 'PARK_MANAGER', 'OPERATIONS_STAFF'],
  },
  {
    key: 'foodCourtRevenue',
    label: 'Doanh thu ẩm thực',
    icon: MdRestaurant,
    color: 'success',
    format: 'currency',
    description: 'Doanh thu từ quầy ăn uống và nhà hàng',
    gridSize: { xs: 12, sm: 6, md: 4, lg: 3 },
    allowedRoles: ['SYSTEM_ADMIN', 'PARK_MANAGER', 'SALES_STAFF'],
  },
  {
    key: 'retailRevenue',
    label: 'Doanh thu bán lẻ',
    icon: MdStorefront,
    color: 'primary',
    format: 'currency',
    description: 'Doanh thu từ các cửa hàng quà lưu niệm',
    gridSize: { xs: 12, sm: 6, md: 4, lg: 3 },
    allowedRoles: ['SYSTEM_ADMIN', 'PARK_MANAGER', 'SALES_STAFF'],
  },
  {
    key: 'refundRate',
    label: 'Tỷ lệ hoàn tiền',
    icon: MdMoneyOff,
    color: 'error',
    format: 'percentage',
    description: 'Tỷ lệ phần trăm đơn hàng bị yêu cầu hoàn tiền',
    gridSize: { xs: 12, sm: 6, md: 4, lg: 3 },
    allowedRoles: ['SYSTEM_ADMIN'],
  },
  {
    key: 'customerSatisfaction',
    label: 'Độ hài lòng khách hàng',
    icon: MdSentimentSatisfied,
    color: 'success',
    format: 'percentage',
    description: 'Điểm đánh giá độ hài lòng trung bình của du khách',
    gridSize: { xs: 12, sm: 6, md: 4, lg: 3 },
    allowedRoles: ['SYSTEM_ADMIN', 'PARK_MANAGER', 'OPERATIONS_STAFF'],
  },
  {
    key: 'netProfit',
    label: 'Lợi nhuận ròng',
    icon: MdAccountBalance,
    color: 'success',
    format: 'currency',
    description: 'Lợi nhuận ròng sau khi trừ tất cả chi phí',
    gridSize: { xs: 12, sm: 6, md: 4, lg: 3 },
    allowedRoles: ['SYSTEM_ADMIN'],
  },
  {
    key: 'operatingCost',
    label: 'Chi phí vận hành',
    icon: MdBuildCircle,
    color: 'warning',
    format: 'currency',
    description: 'Tổng các khoản chi phí vận hành hệ thống',
    gridSize: { xs: 12, sm: 6, md: 4, lg: 3 },
    allowedRoles: ['SYSTEM_ADMIN'],
  },
  {
    key: 'conversionRate',
    label: 'Tỷ lệ chuyển đổi',
    icon: MdSwapHoriz,
    color: 'info',
    format: 'percentage',
    description: 'Tỷ lệ chuyển đổi từ lượt truy cập sang lượt đặt vé',
    gridSize: { xs: 12, sm: 6, md: 4, lg: 3 },
    allowedRoles: ['SYSTEM_ADMIN'],
  },
];
