spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

  datasource:
    hikari:
      maximum-pool-size: 50
      minimum-idle: 10

logging:
  level:
    root: INFO
    com.smartpark: INFO
    org.springframework.security: WARN
    org.hibernate.SQL: ERROR
