export const ROUTES = {
  // Public / Guest
  HOME: '/',
  LOGIN: '/login',
  REGISTER: '/register',
  UNAUTHORIZED: '/unauthorized',
  FORBIDDEN: '/forbidden',
  
  // Customer Portal
  VENUES: '/venues',
  VENUE_DETAILS: '/venues/:id',
  BOOKING: '/booking',
  WALLET: '/wallet',
  TICKETS: '/wallet/tickets',
  MEMBERSHIP: '/membership',
  CHATBOT: '/ai-assistant',
  PROFILE: '/profile',

  // Admin Portal
  ADMIN_DASHBOARD: '/admin/dashboard',
  ADMIN_ANALYTICS: '/admin/analytics',
  ADMIN_USERS: '/admin/users',
  ADMIN_VENUES: '/admin/venues',
  ADMIN_TICKETS: '/admin/tickets',
  ADMIN_ORDERS: '/admin/orders',
  ADMIN_CUSTOMERS: '/admin/customers',
  ADMIN_MEMBERSHIPS: '/admin/memberships',
  ADMIN_LOYALTY: '/admin/loyalty',
  ADMIN_CAMPAIGNS: '/admin/campaigns',
  ADMIN_PROMOTIONS: '/admin/promotions',
  ADMIN_COUPONS: '/admin/coupons',
  ADMIN_VOUCHERS: '/admin/vouchers',
  ADMIN_VISITORS: '/admin/visitors',
  ADMIN_RIDES: '/admin/rides',
  ADMIN_RIDE_CATEGORIES: '/admin/ride-categories',
  ADMIN_GATES: '/admin/gates',
  ADMIN_VALIDATION: '/admin/ticket-validation',
  ADMIN_SCANNER: '/admin/scanner',
  ADMIN_PARKING: '/admin/parking',
  ADMIN_LOCKERS: '/admin/lockers',
  ADMIN_FOOD_COURT: '/admin/food-court',
  ADMIN_RETAIL: '/admin/retail',
  ADMIN_POS: '/admin/pos',
  ADMIN_NOTIFICATIONS: '/admin/notifications',
  ADMIN_SUPPORT: '/admin/support',
  ADMIN_INCIDENTS: '/admin/incidents',
  ADMIN_REPORTS: '/admin/reports',
  ADMIN_EXPORTS: '/admin/exports',
  ADMIN_SETTINGS: '/admin/settings',
} as const;
